### PR TITLE
Fix lint

### PR DESCRIPTION
**Pull request by dopplershift**
Clean up the lint pointed out by the bot. @pelson that thing is awesome!

### CODE REVIEW

**Comment by dopplershift** [comment]
Should also note that this fixes #2 .

**Comment by dopplershift** [comment]
Ok, for some reason something is trying to pull in ordereddict on Python 2.7, but it's not listed in vcrpy's requirements. Anyone seen this before?

**Comment by ocefpaf** [comment]
@dopplershift probably a dependency of a dependency is doing that. Try:

`script: python setup.py install --single-version-externally-managed --record record.txt`

That should prevent `setup.py` from downloading dependencies. (But it might produce a broken package if this goes untested.)

**Comment by dopplershift** [comment]
If I pip install vcrpy, I don't get ordereddict. Another oddity is that you shouldn't need the ordereddict package on 2.7.

**Comment by dopplershift** [comment]
Ok, it bugged me so I tracked it down`funcsigs`:  https://github.com/mgaitan/funcsigs/blob/master/setup.py

(It was far harder to find the authoritative source than it should have been.)
It unconditionally depends on `ordereddict`, even though it tries to import from `collections` first. Nothing to be done about it unless upstream fixes it.

**Comment by ocefpaf** [comment]
> (It was far harder to find the authoritative source than it should have been.)
It unconditionally depends on `ordereddict`, even though it tries to import from `collections` first. Nothing to be done about it unless upstream fixes it.


I've seen package behaving like that before and `python setup.py install --single-version-externally-managed --record record.tx` helped.

**Comment by dopplershift** [comment]
Yeah, that seems to have done it.

**Comment by pelson** [comment]
> Nothing to be done about it unless upstream fixes it.

Let them know and share the love ❤️

**Comment by pelson** [comment]
This is in excellent shape, but the py34 win-64 failure is a known problem with conda-build. If you ```conda smithy rerender``` the feedstock, the CI files will fix the problem.

**Pull request merged**
